### ISSUE TITLE
Turning on the spot resets game

### ISSUE THREAD

**Issue by sebkur** [gnu11111/snake-compose-for-desktop#1]
When I quickly turn around into the opposite direction, the game seems to reset. Score reverts to 0 and the length of the snake is reset to the initial length.

Reproduce for example when the snake is moving rightwards, quickly hit "down" and "left".

It shouldn't be possible to perform that move in the first place. I guess the game logic counts that as hitting the rest of the snake, i.e. game over and starts a new game.

**Comment by gnu11111** [comment]
I was aware of that, but fixed it anyways. You can no longer turn into the opposite direction.

This code is not so much intended as being a fully-fetched game, but serves as a template for implementing a game loop, frame-rate- and screen-resolution-independent rendering, getting input from key-strokes, etc., using Compose-for-Desktop. The Snake game was ideally for that purpose as it has amongst the simplest game logic possible.

**Comment by sebkur** [comment]
Thanks, yes, it's a good simple game, pretty nice for demonstrating how to build a game in general!

**Comment by sebkur** [comment]
I've added it to this collection of compose examples: https://github.com/sebkur/awesome-compose-for-desktop
